spring:
  application:
    name: sleuth
  zipkin:
    base-url: http://localhost:9411 
    sleuth:
      sampler:
        percentage: 1.0
        
server:
  port: 8771

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon
    api-b:
      path: /api-b/**
      serviceId: eureka-client