spring:
  application:
     name: zipkin-server

server:
  port: 9411

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# log
logging:
  config:
    classpath: logback.xml
    
management:
  metrics:
    web:
      server:
        auto-time-requests: false