spring:
  application:
     name: feign
  zipkin:
    base-url: http://localhost:9411 
    sleuth:
      sampler:
        percentage: 1.0
server:
  port: 8091

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/